/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from 'grpc';

export namespace multipackageenum {
    // ResolutionType
    // Test enum
    export enum MultipackageEnum {
        /* Default value */
        DEFAULT = 0,
        /* Default value */
        M1 = 10,
        /* 1 minute */
        M2 = 20,
        /* 2 minutes */
        M5 = 30,
        /* 5 minutes */
        M10 = 40,
        /* 10 minutes */
        M15 = 50,
        /* 15 minutes */
        M30 = 60,
        /* 30 minutes */
        H1 = 70,
        /* 1 hour */
        H2 = 80,
        /* 2 hours */
        H4 = 90,
        /* 4 hours */
        D = 100,
        /* 1 day */
        W = 110,
        /* 1 week */
        MN = 120,
    }
}

